# SPDX-License-Identifier: MIT-0
#
# SPDX-FileCopyrightText: 2024 Tristan Partin <tristan@partin.io>

name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.go"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout go-sd-notify
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout go-sd-notify
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build
        run: |
          go build
